server:
  port: 9090
#spring
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zeal-coder-test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  flyway:
    url: jdbc:mysql://localhost:3306/zeal-coder-test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    user: root
    password: root
    enabled: true
    #    邮箱配置
  mail:
    host: smtp.163.com
    username: ***@163.com
    password: *** # 邮箱开启smtp后显示的授权码
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

#logging
logging:
  level:
    root: info
    com.zealcoder.mapper: info
  file:
    path: logging
    max-size: 10MB
    max-history: 7

